AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

  Exclude:
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/MultilineOperationIndentation:
  Exclude:
    - 'ext/**/*'

Lint/InheritException:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.gemspec'
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'ext/*/extconf.rb'

Style/AndOr:
  EnforcedStyle: conditionals

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/**/*'
    - 'examples/**/*'
    - 'spec/network_helper.rb'

Style/RescueStandardError:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
