AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

  Exclude:
    - vendor/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/MultilineOperationIndentation:
  Exclude:
    - ext/**/*

Lint/InheritException:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - spec/**/*

Metrics/LineLength:
  Max: 120

Style/AndOr:
  Exclude:
    - ext/**/*

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - ext/**/*

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
