language: ruby

rvm:
  - 2.3
  - 2.4

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libtool autotools-dev automake checkinstall check git yasm

  - sudo ./bin/build/libsodium
  - sudo ./bin/build/toxcore

  - sudo mkdir '/etc/ld.so.conf.d/'
  - echo '/usr/local/lib/' | sudo tee -a '/etc/ld.so.conf.d/locallib.conf'
  - sudo ldconfig

before_script:
  - rake compile
