language: ruby

rvm:
  - 2.3
  - 2.4

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsodium18 libsodium-dev
  - sudo git clone https://github.com/TokTok/c-toxcore.git /usr/local/src/c-toxcore/
  - cd /usr/local/src/c-toxcore/
  - sudo autoreconf -i
  - sudo ./configure
  - sudo make
  - sudo make install
  - sudo ldconfig

before_script:
  - rake compile
