language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libtool autotools-dev automake checkinstall check git yasm cmake libconfig-dev

before_script:
  - sudo bundle exec rake vendor:libsodium
  - sudo bundle exec rake vendor:libtoxcore

  - sudo mkdir -p '/etc/ld.so.conf.d/'
  - echo '/usr/local/lib/x86_64-linux-gnu/' | sudo tee -a '/etc/ld.so.conf.d/locallib.conf'
  - sudo ldconfig

  - rake compile
