language: ruby

rvm:
  - 2.3
  - 2.4

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libtool autotools-dev automake checkinstall check git yasm libsodium13 libsodium-dev
