language: ruby

rvm:
  - 2.3
  - 2.4

before_install:
  - echo "deb https://pkg.tox.chat/debian stable jessie" | sudo tee /etc/apt/sources.list.d/tox.list
  - wget -qO - https://pkg.tox.chat/debian/pkg.gpg.key | sudo apt-key add -
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update

  - sudo dpkg --install 'spec/deb/libsodium13_1.0.0-1_amd64.deb'
  - sudo dpkg --install 'spec/deb/libsodium-dev_1.0.0-1_amd64.deb'

  - sudo apt-get install -y libtoxcore-toktok libtoxcore-toktok-dev

  - sudo ldconfig

before_script:
  - rake compile
