language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autopoint yasm libconfig-dev libc-bin

install: bundle install --jobs 3 --retry 3 --without examples

before_script:
  - rake vendor:install:libsodium
  - rake vendor:install:opus
  - rake vendor:install:libvpx
  - rake vendor:install:libtoxcore
  - rake vendor:install:gstreamer
  - rake vendor:install:gst-plugins-base

  - ls -l vendor/lib/
  - ldd vendor/lib/libgstreamer-1.0.so
  - ldd vendor/lib/libgstaudio-1.0.so

  - rake compile:tox
  - rake compile:gst-plugins-tox

  - ldd lib/tox/tox.so
  - ldd lib/gst-plugins-tox.so

script: GST_DEBUG=4 rake
