language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autopoint yasm libconfig-dev

install: bundle install --jobs 3 --retry 3 --without examples

before_script:
  - rake vendor:install:libsodium
  - rake vendor:install:opus
  - rake vendor:install:libvpx
  - rake vendor:install:libtoxcore
  - rake vendor:install:gstreamer
  - rake vendor:install:gst-plugins-base

  - rake compile
