language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y yasm libconfig-dev libgstreamer1.0-dev

install: bundle install --jobs 3 --retry 3 --without examples

before_script:
  - rake vendor:install
  - rake compile
