language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y yasm libconfig-dev libogg-dev

install: bundle install --jobs 3 --retry 3 --without examples

before_script:
  - rake vendor:install:libsodium
  - rake vendor:install:opus
  - rake vendor:install:libvpx
  - rake vendor:install:libtoxcore
  - rake vendor:install:opusfile

  - rake compile:tox
  - rake compile:opus_file
